export const CLEAR_SELECTED_ITEMS = 'CLEAR_SELECTED_ITEMS';
export const GET_SELECTED_ITEMS = 'GET_SELECTED_ITEMS';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SELECT_ITEM = 'SELECT_ITEM';
export const SET_ITEMS_FILTER = 'SET_ITEMS_FILTER';
